import movie1 from './assets/movie1.jpg';
import movie2 from './assets/movie2.jpg';
import movie3 from './assets/movie3.jpg';
import movie4 from './assets/movie4.jpg';
import movie5 from './assets/movie5.jpg';
import movie6 from './assets/movie6.jpg';
import movie7 from './assets/movie7.jpg';
import movie8 from './assets/movie8.jpg';
import movie9 from './assets/movie9.jpg';


export const moviesData=[{id:Math.random(),img:movie1,titre:"Joker",rate:"3",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie2,titre:"Bohemian Rhapsody",rate:"3",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie3,titre:"Avatar",rate:"2",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie4,titre:"Kill Bill",rate:"4",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie5,titre:"Tatanic",rate:"5",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie6,titre:"La La Land",rate:"2",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie7,titre:"Le Seigneur des anneaux",rate:"1",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie8,titre:"Django Unchained",rate:"3",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"},
{id:Math.random(),img:movie9,titre:"Mookuthi",rate:"5",description :" Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through...",trailerUrl:"https://www.youtube.com/"}
]
